# <center> Introduction to Pytorch </center>

In [3]:
from __future__ import print_function
import torch

In [5]:
# create 2 * 4 matrix unintialized
x = torch.empty(2, 4)
print(x)

tensor([[2.4591e+32, 4.5587e-41, 2.4591e+32, 4.5587e-41],
        [4.4842e-44, 0.0000e+00, 8.9683e-44, 0.0000e+00]])


In [6]:
# create 2*4 initialized matrix
x = torch.rand(2, 4)
print(x)

tensor([[0.4534, 0.7658, 0.3839, 0.4887],
        [0.0223, 0.1120, 0.4434, 0.1005]])


In [8]:
x = torch.zeros(2, 4, dtype=torch.float64)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)


In [10]:
# create tensor from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
age = [80, 60, 18, 32]
a = torch.tensor(age)
a

tensor([80, 60, 18, 32])

In [12]:
m = torch.tensor([[80,1.2],[60,2.5], [18,1], [32,0.5]])
m

tensor([[80.0000,  1.2000],
        [60.0000,  2.5000],
        [18.0000,  1.0000],
        [32.0000,  0.5000]])

In [13]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
torch.linspace(-1,1,5)

tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])

In [15]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
torch.empty(2,3)

tensor([[-2.1573e+30,  3.0799e-41, -6.2030e+30],
        [ 3.0799e-41,  0.0000e+00,  0.0000e+00]])

In [21]:
m

tensor([[80.0000,  1.2000],
        [60.0000,  2.5000],
        [18.0000,  1.0000],
        [32.0000,  0.5000]])

In [22]:
m.shape

torch.Size([4, 2])

In [23]:
m.size()

torch.Size([4, 2])

In [26]:
m.flatten()
m

tensor([[80.0000,  1.2000],
        [60.0000,  2.5000],
        [18.0000,  1.0000],
        [32.0000,  0.5000]])

In [29]:
a = a.reshape(4,1)
a

tensor([[80],
        [60],
        [18],
        [32]])

In [32]:
x = torch.rand(10,2)
x

tensor([[0.0357, 0.9275],
        [0.4853, 0.5405],
        [0.8861, 0.9857],
        [0.3360, 0.6526],
        [0.4033, 0.5973],
        [0.9901, 0.0470],
        [0.7946, 0.7926],
        [0.7717, 0.3099],
        [0.6082, 0.0154],
        [0.2020, 0.1046]])

In [35]:
x.flatten()
x.shape

torch.Size([10, 2])

In [36]:
a[-1]

tensor([32])

In [38]:
a.dim()

2

In [39]:
a.dtype

torch.int64

In [40]:
torch.rand(5,5)

tensor([[0.1849, 0.1582, 0.0406, 0.2041, 0.5110],
        [0.4609, 0.2342, 0.4626, 0.9362, 0.4026],
        [0.1844, 0.3886, 0.6392, 0.9390, 0.7971],
        [0.8240, 0.2545, 0.6445, 0.2491, 0.1719],
        [0.2946, 0.3887, 0.5386, 0.6416, 0.2839]])

In [41]:
torch.randn(5,5)

tensor([[-0.1237, -0.0374, -0.7308, -0.7619, -0.1576],
        [-1.5296,  1.6068, -0.4476,  0.8524,  0.3583],
        [ 0.2278,  0.0742, -0.2976,  0.4076,  0.8653],
        [-0.5302, -0.5782, -0.2758,  1.2492, -0.9742],
        [-1.6981,  1.0741, -0.1952, -0.2627,  1.0546]])

In [46]:
torch.random.manual_seed(3)
x = torch.rand(8,2)
x

tensor([[0.0043, 0.1056],
        [0.2858, 0.0270],
        [0.4716, 0.0601],
        [0.7719, 0.7437],
        [0.5944, 0.8879],
        [0.4510, 0.7995],
        [0.1498, 0.4015],
        [0.0542, 0.4594]])

In [47]:
x = torch.ones(5,2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [48]:
y = torch.zeros(5,2)
y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [50]:
z= torch.stack((x,y))
z

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [51]:
w = torch.cat((x,y))
w

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [53]:
price = torch.tensor([1,0.1,4,2])
price.shape

torch.Size([4])

In [54]:
price.reshape(-1,1).shape

torch.Size([4, 1])

In [62]:
data = torch.randint(25,40, size=(10,))
data

tensor([33, 33, 38, 35, 28, 36, 39, 32, 27, 30])

In [63]:
data[:7]

tensor([33, 33, 38, 35, 28, 36, 39])

In [64]:
data[5:7]

tensor([36, 39])

In [65]:
data = torch.randint(25,40, size=(10,3))
data

tensor([[33, 26, 29],
        [30, 34, 34],
        [28, 33, 27],
        [35, 29, 36],
        [27, 35, 28],
        [35, 30, 35],
        [25, 38, 36],
        [37, 25, 29],
        [33, 27, 32],
        [38, 35, 26]])

In [83]:
data[:,2].float().mean()

tensor(31.2000)

In [84]:
a = torch.arange(1,11)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
a+3

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [86]:
torch.log(a.float())

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794, 2.1972,
        2.3026])